import Head from "next/head";

import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import Image from "next/image";
import me from "../public/me.jpg"
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import { FaCss3 } from 'react-icons/fa'
import { DiJavascript1 } from 'react-icons/di'
import { FaHtml5 } from 'react-icons/fa'
import { FaJava } from 'react-icons/fa'
import { FaPhp } from 'react-icons/fa'
import { SiMysql } from 'react-icons/si'
import { FaDatabase } from 'react-icons/fa'
import React from 'react'
import dynamic from 'next/dynamic';
import AlertDialog from "./connect-poppup";
import gtad from  "../public/gtad.png"
import b1 from "../public/binder1.jpg"
import b2 from "../public/binder2.jpg"
import a1 from "../public/a1.png"
import a3 from "../public/a3.png"


import { AiFillGithub, AiFillYoutube } from "react-icons/ai";

const ReactPlayer = dynamic(() => import('react-player/lazy'), { ssr: false });


export default function Home() {
  const [darkMode, setDarkMode] = useState(true);
  const [open, setOpen] = useState(false);

  const handleClickOpen = () => {
    setOpen(true);
  };

  const handleClose = () => {
    setOpen(false);
  };

  return (
    // <VideoPlayer/>
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Prabhjit Singh</title>
        <meta name="description" content="Generated by Prabhjit Singh" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-20">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <div>
              <h1 className="font-burtons text-xl">Prabhjit Singh</h1>
              <h2 className="font-burtons text-sm">singhprabhjit5290@gmail.com</h2>
            </div>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r cursor-pointer from-violet-900 to-blue-400 text-white px-4 py-2 border-none rounded-md ml-8"
                  onClick={handleClickOpen} 
                >
                  Let's connect!
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-violet-700 font-medium dark:text-violet-500 md:text-6xl">
              Prabhjit Singh
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Computer Studies and Information Systems student at Douglas College.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Computer studies and Information systems student with 3.7 GPA and profound knowledge in object-
              oriented programming, web development, and software development paradigms. Self-
              motivated and self-sufficient in troubleshooting problems.
            </p>

            <div className="mx-auto rounded-full w-80 h-80 relative  overflow-hidden mt-10 md:h-96 md:w-96">
              <Image src={me} layout="fill" objectFit="cover" />
            </div>
            
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Technical and coding skills</h3>

            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Throughout my time at Douglas College, I have become proficient in multiple programming
              languages through varoius courses and group projects.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <div className="flex items-center justify-center mx-auto">
                <FaHtml5 className="bg-gradient-to-r from-red-400 to-emerald-800 text-white p-4 ml-4 border-none rounded-md" style={{ fontSize: '80' }} />
                <FaCss3 className="bg-gradient-to-r from-violet-900 to-blue-400 text-white p-4 ml-4 border-none rounded-md" style={{ fontSize: '80' }} />
                <DiJavascript1 className="bg-gradient-to-r from-teal-700 to-cyan-500 text-white p-4 ml-4 border-none rounded-md" style={{ fontSize: '80' }} />
              </div>

              <h3 className="text-lg font-medium pt-8 pb-2  ">
                HTML, CSS and JavaScript
              </h3>
              <p className="py-2">
                Expertise in JavaScript, HTML and CSS demonstrated by <span className=" text-blue-800">A+ Advanced Web Programming with JavaScript & AJAX </span>and
                <span className=" text-blue-800"> A- in the Multimedia Web development </span> courses.
              </p>

            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <div className="flex items-center justify-center mx-auto">
                <p className="bg-gradient-to-r from-red-400 to-emerald-800 text-white p-4 ml-4 border-none rounded-md" style={{ fontSize: '30px' }}>C#</p>
                <FaJava className="bg-gradient-to-r from-violet-900 to-blue-400 text-white p-4 ml-4 border-none rounded-md" style={{ fontSize: '80' }} />
                <FaPhp className="bg-gradient-to-r from-teal-700 to-cyan-500 text-white p-4 ml-4 border-none rounded-md" style={{ fontSize: '80' }} />
              </div>

              <h3 className="text-lg font-medium pt-8 pb-2 ">
                C#, Java and PHP
              </h3>
              <p className="py-2">
                Excellence in Java, acquired from using it primarily for developing software
                products. Used PHP in back-end development for weekly lab projects in the<span className=" text-blue-800"> Web based scripting </span> course.
                Proficiency in C# demonstrated by <span className=" text-blue-800">A+ in Programming with C# </span> course.
              </p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <div className="flex items-center justify-center mx-auto">
                <SiMysql className="bg-gradient-to-r from-violet-900 to-blue-400 text-white p-4 ml-4 border-none rounded-md" style={{ fontSize: '80' }} />
                <FaDatabase className="bg-gradient-to-r from-teal-700 to-cyan-500 text-white p-4 ml-4 border-none rounded-md" style={{ fontSize: '80' }} />
              </div>
              <h3 className="text-lg font-medium pt-8 pb-2 ">Relational and Non-relational Databases</h3>
              <p className="py-2">
                Expertice in Relational and Non-relational Database and DBMS, demonsterated by<span className=" text-blue-800"> A+ in Database 1 and
                  Database 2 </span>courses. Used SQLite, MySql and MongoDB for different projects over the course of studies.
              </p>

            </div>
          </div>
          <AlertDialog open={open} handleClickOpen={handleClickOpen} handleClose = {handleClose} />
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Projects</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Following are some of my best projects
            </p>
          </div>

          <div className="flex flex-col gap-5 py-5 lg:flex-row lg:flex-wrap">

            <div className=" flex-1 text-center shadow-lg rounded-xl dark:bg-white" style={{flexBasis:'45%'}}>
              <ReactPlayer style={{padding:'0.5rem',margin:'0 auto 0 auto',maxWidth:'100%'}} url="https://youtu.be/xXnj2lR5UHE" height={'450px'}  controls={true}/>
              <div className=" p-4">
                <h2 className="text-left mb-1">Description</h2>
              <p style={{fontSize:'0.8rem',textAlign:'left'}}>
              A full-stack MERN application for a skateboard store. It is an 
                e-commerce website which allows users to browse, search and add products
                to the cart. It also has an Admin side, allowing admins to add, edit or
                remove a product.
              </p>
              <h2 className="text-left mt-1">Demonstration and Code</h2>
              <div className="flex items-center">
              <a href="https://youtu.be/xXnj2lR5UHE"><AiFillYoutube style={{fontSize:'2.5rem',color:'maroon'}}/> </a>
              <a href="https://github.com/thandibeer/singhsBoards"><AiFillGithub style={{fontSize:'2rem',color:'black',marginLeft:'15px'}}/> </a>
              </div>
              </div>
              
              {/* <ReactPlayer className=" flex-1 rounded-lg min-h-fit" url="https://www.youtube.com/watch?v=xXnj2lR5UHE" width={"100%"} height={"100%"} controls={true}/> */}
            </div>

            <div className=" flex-1 text-center shadow-lg rounded-xl dark:bg-white" style={{flexBasis:'45%'}}>
            <ReactPlayer style={{padding:'0.5rem',margin:'0 auto 0 auto',maxWidth:'100%'}} url="https://www.youtube.com/watch?v=h2Jul6NomE4" height={'450px'}  controls={true}/>
              <div className=" p-4">
                <h2 className="text-left mb-1">Description</h2>
              <p style={{fontSize:'0.8rem',textAlign:'left'}}>
               A Spring Boot application for peer-to-peer vehicle renting with Thymeleaf using Java and JPA.
               Created the user interface using HTML, CSS, and JavaScript. Used SCRUM as an Agile framework for development. 
               Used GitHub for version control and Heroku with ClearDB for deployment.
              </p>
              <h2 className="text-left mt-1">Demonstration and Code</h2>
              <div className="flex items-center">
              <a href="https://www.youtube.com/watch?v=h2Jul6NomE4"><AiFillYoutube style={{fontSize:'2.5rem',color:'maroon'}}/> </a>
              <a href="https://github.com/thandibeer/GetAwayDrives"><AiFillGithub style={{fontSize:'2rem',color:'black',marginLeft:'15px'}}/> </a>
              </div>
              </div>
            </div>

            <div className=" flex-1 text-center shadow-lg rounded-xl dark:bg-white" style={{flexBasis:'45%'}} >
              <div style={{display:'flex',flexFlow:'row nowrap',maxHeight:'420px',justifyContent:'space-evenly'}}>
              <Image
                style={{borderRadius:'1.5rem',objectFit:'contain',padding:'0.5rem',maxWidth:'49%'}}
                src={b1}
              />
              <Image
                style={{borderRadius:'1.5rem',objectFit:'contain',padding:'0.5rem',maxWidth:'49%'}}
                src={b2}
              />
              </div>
              
              <div className=" p-4">
                <h2 className="text-left mb-1">Description</h2>
              <p style={{fontSize:'0.8rem',textAlign:'left'}}>
              An Android app named "Binder", developed using Android Studio and Firebase realtime Database. Binder App provides a platform to all the book lovers out there who want to meet someone with similar tastes. 
              This app showcases books as a 'dating profile' and provides potential book matches based on the preferences the 
              user sets in their profile. As with dating apps, a user can swipe to the right or left on each book, depending on 
              their level of interest.
              </p>
              <h2 className="text-left mt-1">Code</h2>
              <div className="flex items-center">
              <a href="https://github.com/AmritaSingh21/BinderProject"><AiFillGithub style={{fontSize:'2rem',color:'black'}}/> </a>
              </div>
              </div>
            </div>
            
            <div className=" flex-1 text-center shadow-lg rounded-xl dark:bg-white" style={{flexBasis:'45%'}}>
              <div style={{display:'flex',flexFlow:'row nowrap',maxHeight:'420px',justifyContent:'space-evenly'}}>
              <Image
                style={{borderRadius:'1.5rem',objectFit:'contain',padding:'0.5rem',maxWidth:'49%'}}
                src={a1}
              />
              <Image
                style={{borderRadius:'1.5rem',objectFit:'contain',padding:'0.5rem',maxWidth:'49%'}}
                src={a3}
              />
              </div>
              
              <div className=" p-4">
                <h2 className="text-left mb-1">Description</h2>
              <p style={{fontSize:'0.8rem',textAlign:'left'}}>
              An Android app named "APOP", developed using Android Studio and MySqlite for Database. 
              APOP is a platform for local communities to share or give away books. It makes book sharing easier by 
              enabling users to register the books they want to share and also look for books in his/her locations to borrow.
              </p>
              <h2 className="text-left mt-1">Code</h2>
              <div className="flex items-center">
              <a href="https://github.com/AmritaSingh21/BinderProject"><AiFillGithub style={{fontSize:'2rem',color:'black'}}/> </a>
              </div>
              </div>
            </div>
            
          </div>
        </section>
      </main>
    </div>
  );
}